basePath: /v2
info:
  contact: {}
  description: This is a sample server that says "Hello world!".
  title: Swagger Example API by Jeff
  version: "1.0"
paths:
  /sayhello:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Hello world!
          schema:
            type: string
      summary: Responds by saying "Hello world!"
      tags:
      - messages
swagger: "2.0"